export const DEVICE_STATE_FETCHED = 'DEVICE_STATE_FETCHED';
export const DEVICE_STATE_LOADING = 'DEVICE_STATE_LOADING';
export const READING_UPDATING = 'READING_UPDATING';
export const READING_STATUS_UPDATED = 'READING_STATUS_UPDATED';
export const DEVICE_STATE_FETCH_FAILED = 'DEVICE_STATE_FETCH_FAILED';
export const READING_UPDATION_FAILED = 'READING_UPDATION_FAILED';
export const SEARCH_TEXT_UPDATED = 'SEARCH_TEXT_UPDATED';
